export const GET_ALL_VACCINATION_PLACE = "GET_ALL_VACCINATION_PLACE"
export const CREATE_VACCINATION_PLACE = "CREATE_VACCINATION_PLACE"
export const EDIT_VACCINATION_PLACE = "EDIT_VACCINATION_PLACE"
export const DELETE_VACCINATION_PLACE = "DELETE_VACCINATION_PLACE"